============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-3.7.4, py-1.6.0, pluggy-0.7.1
rootdir: /home/antonio/workspace/pyco/pyco, inifile:
plugins: timeout-1.3.2
timeout: 1000.0s
timeout method: signal
timeout func_only: False
collected 1 item

pyco/tests/test_spi.py Decomposing Specification...
	multiple output clusters, processing port adcbit_6
	multiple output clusters, processing port adcbit_4
	multiple output clusters, processing port adcbit_0
	multiple output clusters, processing port adcbit_1
	multiple output clusters, processing port adcbit_7
	multiple output clusters, processing port adcbit_2
	multiple output clusters, processing port ready
	multiple output clusters, processing port adcbit_3
	multiple output clusters, processing port adcbit_5
Instantiate Solvers...
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
* 
loops until success:
2

* 
loops until success:
6

* 
loops until success:
6

* 
loops until success:
6

* 
loops until success:
7

* 
loops until success:
7

* 
loops until success:
7

F

=================================== FAILURES ===================================
_______________________________ test_adc8_int_sd _______________________________

spi_lib8_int_sd = <pyco.library.ContractLibrary object at 0x7f7c4b6d5690>

    def test_adc8_int_sd(spi_lib8_int_sd):
        '''
        Performs simple synthesis
        '''
    
        spec = Spec8int('G1')
    
        interface = SynthesisInterface(spi_lib8_int_sd, [spec])
    
        adc = interface.get_component('ADC8int')
        # interface.use_component(adc)
        interface.use_connected_spec(adc, 'analog', 'analog')
        # interface.synthesize(max_depth=4, library_max_redundancy=1)
>       interface.synthesize(max_depth=4, library_max_redundancy=1, decompose=True)

pyco/tests/test_spi.py:1129: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pyco/synthesis.py:150: in synthesize
    decompose=decompose)
pyco/z3_interface.py:387: in synthesize
    results.append(result_queue.get())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <multiprocessing.queues.Queue object at 0x7f7c4b58cad0>, block = True
timeout = None

    def get(self, block=True, timeout=None):
        if block and timeout is None:
            self._rlock.acquire()
            try:
>               res = self._recv()
E               Failed: Timeout >1000.0s

/usr/lib/python2.7/multiprocessing/queues.py:117: Failed
========================= 1 failed in 1000.16 seconds ==========================
* 
loops until success:
3

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 325, in _exit_function
    p.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception TypeError: "'NoneType' object is not callable" in <object repr() failed> ignored
Exception TypeError: "'NoneType' object is not callable" in <object repr() failed> ignored
Exception TypeError: "'NoneType' object is not callable" in <bound method Context.__del__ of <z3.z3.Context instance at 0x7f7c4b59b7e8>> ignored
============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-3.7.4, py-1.6.0, pluggy-0.7.1
rootdir: /home/antonio/workspace/pyco/pyco, inifile:
plugins: timeout-1.3.2
timeout: 1000.0s
timeout method: signal
timeout func_only: False
collected 1 item

pyco/tests/test_spi.py Process RefinementChecker-18:1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/antonio/workspace/pyco/pyco/z3_thread_manager.py", line 267, in run
    self.manager.result_queue, self.terminate_event)
  File "/home/antonio/workspace/pyco/pyco/counterxample_analysis.py", line 335, in counterexample_analysis
    max_depth=manager.max_depth)
  File "/home/antonio/workspace/pyco/pyco/counterxample_analysis.py", line 1677, in exists_forall_learner
    passed, trace = verify_candidate(left, all_specs_formula)
  File "/home/antonio/workspace/pyco/pyco/counterxample_analysis.py", line 1902, in verify_candidate
    return_trace=True)
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 254, in verify_tautology
    return_trace=return_trace)
  File "/home/antonio/workspace/pycolite/pycolite/nuxmv.py", line 213, in verify_tautology_smv
    stderr=STDOUT, )
  File "/usr/lib/python2.7/subprocess.py", line 568, in check_output
    output, unused_err = process.communicate()
  File "/usr/lib/python2.7/subprocess.py", line 792, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
*Process SinglePortSolver-18:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/antonio/workspace/pyco/pyco/z3_single_port_solver.py", line 148, in run
    spec, contract_list, params_assign) = thread_manager.synthesize()
  File "/home/antonio/workspace/pyco/pyco/z3_thread_manager.py", line 135, in synthesize
    return self.quit(wait=True)
  File "/home/antonio/workspace/pyco/pyco/z3_thread_manager.py", line 161, in quit
    thread.join()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 145, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 154, in wait
    return self.poll(0)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 135, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt

Decomposing Specification...
	multiple output clusters, processing port adcbit_4
	multiple output clusters, processing port adcbit_6
	multiple output clusters, processing port adcbit_0
	multiple output clusters, processing port adcbit_1
	multiple output clusters, processing port adcbit_2
	multiple output clusters, processing port adcbit_7
	multiple output clusters, processing port adcbit_5
	multiple output clusters, processing port adcbit_3
	multiple output clusters, processing port ready
Instantiate Solvers...
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
11
* 
loops until success:
2

* 
loops until success:
5

* 
loops until success:
6

* 
loops until success:
6

* 
loops until success:
7

* 
loops until success:
7

* 
loops until success:
7

* 
loops until success:
3

* 
loops until success:
9

.

========================== 1 passed in 339.96 seconds ==========================
